import type { Metadata } from 'next';
import { Manrope,DM_Sans } from 'next/font/google';
import './globals.css';
import React from 'react';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

const dmSans = DM_Sans({
  variable: '--font-dmSans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Praxisphere Platform - Empathy Beyond',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${manrope.variable} ${dmSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
